import type { Metadata } from "next";
import "./globals.css";
import AOSProvider from "@/components/AosProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-[#090D1F] dark:text-[#fff]">
        <AOSProvider>{children}</AOSProvider>
      </body>
    </html>
  );
}
